"""R_001: Professional VAPT Report Generator.

Generates HackerOne/Bugcrowd-style markdown reports with:
- Executive Summary
- Scope & Methodology
- Findings (CVSS, CWE, OWASP MASVS)
- Proof of Concept
- Remediation Steps
- References
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from sentinel.agents.base import BaseAgent
from sentinel.core.finding import Finding, Severity

if TYPE_CHECKING:
    pass


class ReportGeneratorAgent(BaseAgent):
    """Generate professional VAPT reports from scan findings."""

    AGENT_ID = "R_001"
    VULN_CLASS = "VAPT Report Generation"
    PHASE = "Phase 8"

    async def is_applicable(self) -> bool:
        """Always run after scan completes."""
        return True

    async def analyze(self) -> list[Finding]:
        """Generate comprehensive VAPT report."""
        # Fetch all findings from memory
        all_findings = await self.memory.get_findings(
            session_id=self.context.session_id
        )

        if not all_findings:
            return []

        # Filter verified findings
        verified = [f for f in all_findings if f.triage == "True Positive"]

        # Generate report
        report_path = await self._generate_vapt_report(verified)

        # Return meta-finding
        return [
            self._make_finding(
                vuln_class="VAPT Report Generated",
                severity=Severity.INFO,
                confidence=1.0,
                evidence={
                    "report_path": str(report_path),
                    "total_findings": len(all_findings),
                    "verified_findings": len(verified),
                    "critical": len([f for f in verified if f.severity == Severity.CRITICAL]),
                    "high": len([f for f in verified if f.severity == Severity.HIGH]),
                    "medium": len([f for f in verified if f.severity == Severity.MEDIUM]),
                    "low": len([f for f in verified if f.severity == Severity.LOW]),
                },
                recommendation="Review the generated VAPT report for submission to bug bounty programs.",
            )
        ]

    async def _generate_vapt_report(self, findings: list[Finding]) -> Path:
        """Generate markdown VAPT report."""
        report_dir = self.context.workspace / "reports"
        report_dir.mkdir(exist_ok=True)

        report_path = report_dir / f"VAPT_Report_{self.context.session_id}.md"

        # Group findings by severity
        critical = [f for f in findings if f.severity == Severity.CRITICAL]
        high = [f for f in findings if f.severity == Severity.HIGH]
        medium = [f for f in findings if f.severity == Severity.MEDIUM]
        low = [f for f in findings if f.severity == Severity.LOW]

        # Generate report content
        content = self._build_report_content(
            findings=findings,
            critical=critical,
            high=high,
            medium=medium,
            low=low,
        )

        report_path.write_text(content, encoding="utf-8")
        return report_path

    def _build_report_content(
        self,
        findings: list[Finding],
        critical: list[Finding],
        high: list[Finding],
        medium: list[Finding],
        low: list[Finding],
    ) -> str:
        """Build complete VAPT report markdown."""
        pkg = self.context.manifest.get("package", "Unknown")
        version = self.context.manifest.get("version_name", "Unknown")

        report = f"""# Vulnerability Assessment and Penetration Testing Report

## Application: {pkg}
**Version:** {version}<br/>
**Report Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}<br/>
**Session ID:** {self.context.session_id}<br/>
**Generated by:** SENTINEL v1.0

---

## Executive Summary

This report presents the findings of a comprehensive security assessment conducted on the Android application **{pkg}** (version {version}). The assessment employed both static application security testing (SAST) and dynamic application security testing (DAST) methodologies.

### Key Findings

- **Total Vulnerabilities Identified:** {len(findings)}
- **Critical Severity:** {len(critical)}
- **High Severity:** {len(high)}
- **Medium Severity:** {len(medium)}
- **Low Severity:** {len(low)}

### Risk Assessment

"""
        if critical:
            report += f"⚠️ **CRITICAL RISK**: {len(critical)} critical vulnerabilities require immediate remediation.\n\n"
        elif high:
            report += f"⚠️ **HIGH RISK**: {len(high)} high-severity vulnerabilities identified.\n\n"
        else:
            report += "✅ **MODERATE RISK**: No critical or high-severity vulnerabilities detected.\n\n"

        report += """---

## Scope & Methodology

### Scope

- **Target Application:** Android APK
- **Testing Type:** Black-box + Grey-box
- **Analysis Phases:**
  - Phase 0: APK Ingestion & Validation
  - Phase 1: Reconnaissance (Decompilation, Manifest Analysis)
  - Phase 2: Static Application Security Testing (SAST)
  - Phase 3: LLM-Assisted Triage & Verification
  - Phase 4: Dynamic Application Security Testing (DAST)
  - Phase 7: Exploit Chain Correlation

### Methodology

**Static Analysis:**
- JADX decompilation to Java source
- Apktool resource extraction
- Androguard manifest parsing
- Semgrep AST-based pattern matching
- Custom agent-based vulnerability detection

**Dynamic Analysis:**
- mitmproxy network traffic interception
- Frida runtime instrumentation
- Certificate pinning bypass testing
- API security testing

**LLM-Assisted Verification:**
- Multi-provider LLM triage (Groq, Cerebras, Ollama)
- False positive filtering
- Confidence scoring

---

## Findings

"""

        # Critical findings
        if critical:
            report += "### 🔴 Critical Severity\n\n"
            for idx, finding in enumerate(critical, 1):
                report += self._format_finding(idx, finding)

        # High findings
        if high:
            report += "### 🟠 High Severity\n\n"
            for idx, finding in enumerate(high, 1):
                report += self._format_finding(idx, finding)

        # Medium findings
        if medium:
            report += "### 🟡 Medium Severity\n\n"
            for idx, finding in enumerate(medium, 1):
                report += self._format_finding(idx, finding)

        # Low findings
        if low:
            report += "### 🟢 Low Severity\n\n"
            for idx, finding in enumerate(low, 1):
                report += self._format_finding(idx, finding)

        # Recommendations
        report += """---

## Recommendations

### Immediate Actions (Critical/High)

"""
        for finding in critical + high:
            report += f"- **{finding.vuln_class}**: {finding.recommendation}\n"

        report += """

### Short-term Actions (Medium)

"""
        for finding in medium[:5]:  # Top 5 medium
            report += f"- **{finding.vuln_class}**: {finding.recommendation}\n"

        report += """

### Long-term Actions

- Implement secure coding training for development team
- Establish regular security testing cadence (quarterly)
- Integrate SAST/DAST into CI/CD pipeline
- Conduct third-party security audit

---

## References

- OWASP Mobile Application Security Verification Standard (MASVS)
- OWASP Mobile Top 10 2024
- CWE/SANS Top 25 Most Dangerous Software Errors
- NIST SP 800-163 Rev. 1: Vetting the Security of Mobile Applications

---

## Appendix

### Testing Environment

- **SENTINEL Version:** 1.0
- **Analysis Date:** {datetime.now().strftime("%Y-%m-%d")}
- **APK SHA-256:** {self.context.apk_hash or "N/A"}
- **APK Size:** {self.context.apk_path.stat().st_size if self.context.apk_path else 0} bytes

### Agent Coverage

- **Static Agents:** 15
- **Dynamic Agents:** 4
- **Correlation Agents:** 1
- **Total Agents:** 20

---

**Report End**

*This report is confidential and intended solely for the application owner. Unauthorized distribution is prohibited.*
"""

        return report

    def _format_finding(self, idx: int, finding: Finding) -> str:
        """Format a single finding for the report."""
        evidence_str = json.dumps(finding.evidence, indent=2)

        return f"""#### {idx}. {finding.vuln_class}

**Agent:** {finding.agent_id}<br/>
**Confidence:** {finding.confidence:.0%}<br/>
**CWE:** {finding.evidence.get('cwe', 'N/A')}<br/>
**OWASP:** {finding.owasp or 'N/A'}<br/>
**MASVS:** {finding.masvs or 'N/A'}

**Description:**

{finding.evidence.get('description', 'No description available.')}

**Evidence:**

```json
{evidence_str}
```

**Impact:**

{self._get_impact_description(finding)}

**Proof of Concept:**

{finding.poc or 'Manual verification required.'}

**Remediation:**

{finding.recommendation}

**CVSS Vector:** {finding.cvss_vector or 'N/A'}

---

"""

    def _get_impact_description(self, finding: Finding) -> str:
        """Generate impact description based on vulnerability class."""
        impacts = {
            Severity.CRITICAL: "This vulnerability poses an immediate and severe risk to the application and its users. Exploitation could lead to complete compromise of user data, authentication bypass, or remote code execution.",
            Severity.HIGH: "This vulnerability represents a significant security risk. Successful exploitation could result in unauthorized access to sensitive data, privilege escalation, or denial of service.",
            Severity.MEDIUM: "This vulnerability could be exploited under certain conditions to compromise security. While not immediately critical, it should be addressed in the next development cycle.",
            Severity.LOW: "This vulnerability represents a minor security concern. While exploitation is unlikely or limited in impact, remediation is recommended as part of security hardening.",
        }
        return impacts.get(finding.severity, "Impact assessment pending.")
